# Generated by Django 2.1.7 on 2019-03-02 20:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_link', models.URLField(blank=True, max_length=512, null=True)),
                ('wiki_link', models.URLField(max_length=512)),
                ('kingdom', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('cclass', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('genus', models.CharField(blank=True, max_length=50, null=True)),
                ('species', models.CharField(max_length=50)),
                ('cap_shapes', multiselectfield.db.fields.MultiSelectField(choices=[('campanulate', 'campanulate'), ('conical', 'conical'), ('convex', 'convex'), ('depressed', 'depressed'), ('flat', 'flat'), ('infundibuliform', 'infundibuliform'), ('offset', 'offset'), ('ovate', 'ovate'), ('umbilicate', 'umbilicate'), ('umbonate', 'umbonate'), ('no', 'no'), ('na', 'NA')], max_length=96)),
                ('hymenium_types', multiselectfield.db.fields.MultiSelectField(choices=[('gills', 'gills'), ('pores', 'pores'), ('smooth', 'smooth'), ('ridges', 'ridges'), ('teeth', 'teeth'), ('gleba', 'gleba')], max_length=37)),
                ('gill_types', multiselectfield.db.fields.MultiSelectField(choices=[('adnate', 'adnate'), ('adnexed', 'adnexed'), ('decurrent', 'decurrent'), ('emarginate', 'emarginate'), ('free', 'free'), ('seceding', 'seceding'), ('sinuate', 'sinuate'), ('subdecurrent', 'subdecurrent'), ('no', 'no'), ('na', 'NA')], max_length=76)),
                ('stipe_characters', multiselectfield.db.fields.MultiSelectField(choices=[('bare', 'bare'), ('ring', 'ring'), ('volva', 'volva'), ('ring-and-volva', 'ring and volva'), ('cortina', 'cortina'), ('na', 'NA')], max_length=41)),
                ('sporeprint_colors', multiselectfield.db.fields.MultiSelectField(choices=[('black', 'black'), ('blackish-brown', 'blackish-brown'), ('brown', 'brown'), ('buff', 'buff'), ('cream', 'cream'), ('ochre', 'ochre'), ('olive', 'olive'), ('olive-brown', 'olive-brown'), ('pink', 'pink'), ('pinkish-brown', 'pinkish-brown'), ('purple', 'purple'), ('purple-black', 'purple-black'), ('purple-brown', 'purple-brown'), ('reddish-brown', 'reddish-brown'), ('salmon', 'salmon'), ('tan', 'tan'), ('white', 'white'), ('yellow', 'yellow'), ('yellow-orange', 'yellow-orange'), ('yellow-brown', 'yellow-brown')], max_length=178)),
                ('ecologies', multiselectfield.db.fields.MultiSelectField(choices=[('mycorrhizal', 'mycorrhizal'), ('parasitic', 'parasitic'), ('saprotrophic', 'saprotrophic')], max_length=34)),
                ('edibility', multiselectfield.db.fields.MultiSelectField(choices=[('choice', 'choice'), ('edible', 'edible'), ('inedible', 'inedible'), ('unpalatable', 'unpalatable'), ('caution', 'caution'), ('psychoactive', 'psychoactive'), ('poisonous', 'poisonous'), ('allergenic', 'allergenic'), ('deadly', 'deadly'), ('unknown', 'unknown')], max_length=91)),
            ],
            options={
                'verbose_name_plural': 'mushrooms',
                'ordering': ['name'],
            },
        ),
    ]
