# Generated by Django 2.1.7 on 2019-03-16 21:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wikiurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='cap_shapes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('campanulate', 'campanulate'), ('conical', 'conical'), ('convex', 'convex'), ('depressed', 'depressed'), ('flat', 'flat'), ('infundibuliform', 'infundibuliform'), ('offset', 'offset'), ('ovate', 'ovate'), ('umbilicate', 'umbilicate'), ('umbonate', 'umbonate'), ('no', 'no'), ('na', 'NA')], max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='cclass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='ecologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mycorrhizal', 'mycorrhizal'), ('parasitic', 'parasitic'), ('saprotrophic', 'saprotrophic')], max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='edibility',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('choice', 'choice'), ('edible', 'edible'), ('inedible', 'inedible'), ('unpalatable', 'unpalatable'), ('caution', 'caution'), ('psychoactive', 'psychoactive'), ('poisonous', 'poisonous'), ('allergenic', 'allergenic'), ('deadly', 'deadly'), ('unknown', 'unknown')], max_length=91, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='gill_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('adnate', 'adnate'), ('adnexed', 'adnexed'), ('decurrent', 'decurrent'), ('emarginate', 'emarginate'), ('free', 'free'), ('seceding', 'seceding'), ('sinuate', 'sinuate'), ('subdecurrent', 'subdecurrent'), ('no', 'no'), ('na', 'NA')], max_length=76, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='hymenium_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gills', 'gills'), ('pores', 'pores'), ('smooth', 'smooth'), ('ridges', 'ridges'), ('teeth', 'teeth'), ('gleba', 'gleba')], max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='kingdom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='sporeprint_colors',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('black', 'black'), ('blackish-brown', 'blackish-brown'), ('brown', 'brown'), ('buff', 'buff'), ('cream', 'cream'), ('ochre', 'ochre'), ('olive', 'olive'), ('olive-brown', 'olive-brown'), ('pink', 'pink'), ('pinkish-brown', 'pinkish-brown'), ('purple', 'purple'), ('purple-black', 'purple-black'), ('purple-brown', 'purple-brown'), ('reddish-brown', 'reddish-brown'), ('salmon', 'salmon'), ('tan', 'tan'), ('white', 'white'), ('yellow', 'yellow'), ('yellow-orange', 'yellow-orange'), ('yellow-brown', 'yellow-brown')], max_length=178, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='stipe_characters',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('bare', 'bare'), ('ring', 'ring'), ('volva', 'volva'), ('ring-and-volva', 'ring and volva'), ('cortina', 'cortina'), ('na', 'NA')], max_length=41, null=True),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='wiki_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
